easy_admin:
    site_name: 'SMB'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Langage:
            class: App\Entity\Langage
            form:
                fields:
                    - libelle
                    - { property: 'frameworks', type_options: { by_reference: false} }
        Framework:
            class: App\Entity\Framework
        VersionFramework:
            class: App\Entity\VersionFramework
        Experience:
            class: App\Entity\Experience
        Formation:
            class: App\Entity\Formation
        Information:
            class: App\Entity\Information
        CurriculumVitae:
            class: App\Entity\CurriculumVitae
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - intitule
                    - nom
                    - prenom
                    - { property: 'dateNaissance', type: 'birthday', label: 'Né(e) le' }
                    - mail
                    - adresse
                    - ville
                    - numPortable